[package]
name = "speck-cipher"
version = "0.1.0"
edition = "2021"

[dependencies]
cipher = "0.4.4"
generic-array = "1.0.0"
hex-literal = "0.4.1"
rand = "0.8.5"

[dev-dependencies]
criterion = { version = "0.5", features = ['real_blackbox'] }

[[bench]]
name = "speck_benchmark"
harness = false
